# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do


  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end


  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
        task: "clean assemble",
        build_type: 'buildTypeAlpha',
        flavor: 'Alpha'
        )

    crashlytics(
        notes: git_branch,
        api_token: 'f30a0b32e6ac982df866253afd67b9ea644ae43c',
        build_secret: 'ccde11f7fb5d18037c74848cebac7b0d9b490909140bb4cc888d8d6c620a7057'
        )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end



  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end


end
